### ISSUE TITLE
Throws an exception

### ISSUE THREAD

**Issue by ipeychev** [codemix/babel-plugin-macros#2]
Hello,

I tried to use it and copied the "DEFINE_MACRO" macro from the README, but then I got this error:

```
Trace: Path#remove has been renamed to Path#dangerouslyRemove, removing a node is extremely dangerous so please refrain using it.
    at NodePath.remove (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/path/removal.js:29:11)
    at defineMacro (/Users/test/projects/test/node_modules/babel-plugin-macros/lib/index.js:40:10)
    at runMacro (/Users/test/projects/test/node_modules/babel-plugin-macros/lib/index.js:172:5)
    at NodePath.enter (/Users/test/projects/test/node_modules/babel-plugin-macros/lib/index.js:234:13)
    at NodePath.call (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
    at NodePath.visit (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/path/context.js:146:8)
    at TraversalContext.visitSingle (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/context.js:105:12)
    at TraversalContext.visit (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/context.js:117:19)
    at Function.traverse.node (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at NodePath.visit (/Users/test/projects/test/node_modules/gulp-babel/node_modules/babel-core/lib/babel/traversal/path/context.js:163:26)
```

I have the babel which comes with "gulp-babel": "^5.1.0"

**Comment by phpnode** [comment]
@ipeychev hey, unfortunately babel's plugin API has changed since the last release and I've not yet had chance to update it due to other commitments. PRs welcome :)

**Comment by ipeychev** [comment]
To change the "remove" function with "dangerouslyRemove" is not hard and I just did it, however, the tests are currently broken and I don't think this is due to "remove" change. The errors are something like:

```
Babel Macros
    1) should compile macros in "id"
    2) should compile macros in "double"
    3) should compile macros in "triple"
    4) should compile macros in "map"
    5) should compile macros in "map-filter"
    6) should compile macros in "some"


  0 passing (567ms)
  6 failing

  1) Babel Macros should compile macros in "id":
     TypeError: unknown: undefined is not a function
      at src/index.js:65:7
      at runMacro (src/index.js:161:5)
      at NodePath.enter (src/index.js:220:13)
      at runTest (test/index.js:3:25)
      at Context.<anonymous> (test/index.js:26:5)

... more here
```

Do you have an idea why is that?

Thanks,

**Comment by phpnode** [comment]
Pretty sure that there were some changes around `generateUidIdentifier()` or similar which we [make use of](https://github.com/codemix/babel-plugin-macros/blob/master/src/index.js#L83) I think that method also got renamed.
